### ISSUE TITLE
mkdir: Permission denied

### ISSUE THREAD

**Issue by matiaslina** [JJ/raku-container-action#1]
Hi @JJ ! 

Some time ago I've setup this action for the [Matrix::Client](https://github.com/matiaslina/Matrix-Client/) library. I didn't pay to much attention to the errors that day, but today I've tried to run it again and the action seems to be broken.

The problem seems to be with the `mkdir` directive on the Dockerfile

```
  Step 3/6 : RUN mkdir /test
   ---> Running in 511462a76851
  mkdir: can't create directory '/test': Permission denied
  The command '/bin/sh -c mkdir /test' returned a non-zero code: 1
``` 

[full log](https://github.com/matiaslina/Matrix-Client/runs/1444848251?check_suite_focus=true#step:2:32)

I don't know if there's something that I'm missing on my configuration file (https://github.com/matiaslina/Matrix-Client/blob/master/.github/workflows/main.yml) or that `mkdir` is not necessary given that is proceeded by a `VOLUME`

**Comment by JJ** [comment]
I  changed the base images, and this might be the consequence. Thanks for the report, I'll check it out.

**Comment by matiaslina** [comment]
Thanks!

**Comment by bbkr** [comment]
Same error here:

https://github.com/bbkr/TinyID/runs/1540517893?check_suite_focus=true

**Comment by JJ** [comment]
Sorry, I'll try to help you as soon as I possibly can, mid-next week at the latest.

**Comment by JJ** [comment]
That does not fix it. Let me see here.
